# Generated by Django 4.2.5 on 2023-09-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=3)),
                ('comment', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
