# Generated by Django 4.2.5 on 2023-09-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0002_coments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coments',
            name='signature',
            field=models.CharField(default='Firma', max_length=50),
        ),
    ]
